---
name: ECR Build Image
description: Builds and may publish and image to the specified Elastic Container Registry(ECR) instance using the provided role and session

inputs:
  aws_region:
    description: AWS region
    required: false
    default: 'us-east-1'
  aws_role_name:
    description: AWS role to use
    required: false
    default: ''
  aws_role_session_name:
    description: AWS role session name to use
    required: false
    default: 'github-actions'
  ecr_repository_name:
    description: Elastic Container Registry(ECR) name
    required: true
  path:
    description: path to build the image in
    required: false
    default: ''
  dockerfile:
    description: Dockerfile to pass to docker
    required: false
    default: 'Dockerfile'
  docker_context:
    description: Docker context to pass to docker build
    required: false
    default: '.'
  docker_target:
    description: The target build stage to build
    required: false
    default: ''
  docker_build_args:
    description: The build arguments to pass to docker
    required: false
    default: ''
  docker_tags:
    description: The docker tags to pass into docker
    required: false
    default: 'latest'
  image_url:
    description: Image url used for annotation per the open containers specification
    required: false
    default: ''
  image_title:
    description: Human-readable title of the image
    required: false
    default: ''
  image_description:
    description: human readable description for the artifact
    required: false
    default: ''
  image_documentation:
    description: URL to find more information on the image
    required: false
    default: ''
  github_username:
    description: This is not used at this time
    required: false
    default: ''
  push:
    description: Flag determining whether to push the built docker image to Elastic Container Registry(ECR)
    required: false
    default: 'false'

runs:
  using: "composite"
  steps:
    - name: Generate Env Vars
      shell: bash
      id: generate-env-vars
      run: |-
        echo 'ECR_REGISTRY_URI=${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com' >>"$GITHUB_OUTPUT"
        echo 'ECR_REPOSITORY_URI=${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com/${{ inputs.ecr_repository_name }}' >>"$GITHUB_OUTPUT"

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-region: ${{ inputs.aws_region }}
        role-to-assume: arn:aws:iam::${{ env.AWS_ACCOUNT_ID }}:role/${{ inputs.aws_role_name }}
        role-session-name: ${{ inputs.aws_role_session_name }}

    - name: Login to ECR
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build Container Image
      shell: bash
      run: |-
        if [ -d '${{ inputs.path }}' ]; then
            cd '${{ inputs.path }}'
        fi

        export DOCKER_BUILDKIT=1

        export ECR_REGISTRY_URI='${{ steps.generate-env-vars.outputs.ECR_REGISTRY_URI }}'
        export ECR_REPOSITORY_URI='${{ steps.generate-env-vars.outputs.ECR_REPOSITORY_URI }}'

        declare -a docker_args=(
            '--progress=plain'
            "--tag=${ECR_REPOSITORY_URI}:${GITHUB_SHA::12}"
            '--file=${{ inputs.dockerfile }}'
            '--build-arg=BUILDKIT_INLINE_CACHE=1'
        )

        IFS=', ' read -r -a docker_tags <<<'${{ inputs.docker_tags }}'
        for docker_tag in "${docker_tags[@]}"; do
            docker_args+=(
                "--cache-from=${ECR_REPOSITORY_URI}:${docker_tag}"
                "--tag=${ECR_REPOSITORY_URI}:${docker_tag}"
            )
        done

        if [ -n "${inputs.docker_build_args}" ]; then
            IFS=', ' read -r -a build_args <<<"${inputs.docker_build_args}"
            for build_arg in "${build_args[@]}"; do
                docker_args+=("--build-arg=${build_args}")
            done
        fi

        if [ -n '${{ inputs.docker_target }}' ]; then
            docker_args+=('--target=${{ inputs.docker_target }}')
        fi

        docker_args+=(
            "--build-arg=org_opencontainers_image_created=$(date -u '+%Y-%m-%dT%H:%M:%SZ')"
            "--build-arg=org_opencontainers_image_source=${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}"
            "--build-arg=org_opencontainers_image_revision=${GITHUB_SHA::12}"
        )

        if [ -n '${{ inputs.image_url }}' ]; then
            docker_args+=('--build-args=org_opencontainers_image_url=${{ inputs.image_url }}')
        fi

        if [ -n '${{ inputs.image_title }}' ]; then
            docker_args+=('--build-args=org_opencontainers_image_title=${{ inputs.image_title }}')
        fi

        if [ -n '${{ inputs.image_description }}' ]; then
            docker_args+=('--build-args=org_opencontainers_image_description=${{ inputs.image_description }}')
        fi

        if [ -n '${{ inputs.image_documentation }}' ]; then
            docker_args+=('--build-args=org_opencontainers_image_documentation=${{ inputs.image_documentation }}')
        fi

        docker build "${docker_args[@]}" '${{ inputs.docker_context }}'

    - name: Push Image
      shell: bash
      if: ${{ inputs.push == 'true' }}
      run: |-
        export ECR_REPOSITORY_URI='${{ steps.generate-env-vars.outputs.ECR_REPOSITORY_URI }}'

        docker push "${ECR_REPOSITORY_URI}:${GITHUB_SHA::12}"

        IFS=', ' read -r -a docker_tags <<<'${{ inputs.docker_tags }}'
        for docker_tag in "${docker_tags[@]}"; do
            docker push "${ECR_REPOSITORY_URI}:${docker_tag}"
        done
